---
title: "MP2"
author: "Cara Krupnikoff-Salkin, Lauren Meyer, and Nicole Reardon"
date: "`r format(Sys.Date(), '%B %e, %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)

library(tidyverse)
library(car)
```


```{r data-cleaning, include = FALSE}
data <- read.csv('MP2_data.csv')

data <- data %>%
  select(choice, worthwhile, connect, waste, value, engage, attend, type, format) %>%
  filter(!row_number() %in% c(1, 2,75,76),
         !is.na(attend)) %>%
  mutate(choice = as.numeric(choice),
         worthwhile = as.numeric(worthwhile),
         connect = as.numeric(connect),
         waste = as.numeric(waste),
         value = as.numeric(value),
         engage = as.numeric(engage),
         attend = as.numeric(attend))

cleaned_data <- data %>%
  mutate(waste_recoded = 6 - waste,
         sum_eventscore = worthwhile + connect + waste_recoded + value + engage + attend,
         avg_eventscore = sum_eventscore / 6)
```


```{r analysis}
cleaned_data %>%
  group_by(type, format) %>%
  summarize(m = mean(avg_eventscore), sd = sd(avg_eventscore), n = n())

model1 <- lm(avg_eventscore ~ type*format, data = cleaned_data)
anova(model1)
#No significant differences. Not even when looking only at the virtual group, or only at the difference between the academic and business virtual groups. Alas. 

leveneTest(avg_eventscore ~ type * format, data = cleaned_data)
#Significant difference, invalid 

plot(model1, which = 1)
plot(model1, which = 2)

ggplot(cleaned_data, aes(x = type, y = avg_eventscore, color = format)) + 
  geom_point() + geom_jitter()
ggplot(cleaned_data, aes(x = type, y = avg_eventscore, fill = format)) + 
  geom_boxplot()
ggplot(cleaned_data, aes(x = format, y = avg_eventscore, fill = type)) + 
  geom_boxplot()
```

# Exploring Business
```{r}
cleaned_data %>%
  group_by(type) %>%
  summarize(n = n(),
            s = sd(choice),
            m = mean(choice))

mod_choice <- lm(choice ~ type * format, cleaned_data)
anova(mod_choice)

no_business <- cleaned_data %>%
  filter(type != 'business')

mod_nobus <- lm(avg_eventscore ~ type*format, data = no_business)
anova(mod_nobus)

leveneTest(avg_eventscore ~ type * format, data = no_business)
# perhaps removing business makes the conditions for the model better
```

```{r}
#Correlation testing the response scale score. 
#Dropping the Choice and Connect variables (both only loosely correlated with the rest of the group) creates a stronger scale score.
library(psych)
corr.test(select(cleaned_data, worthwhile, waste_recoded, value, engage, attend))$r
psych::alpha(select(cleaned_data, worthwhile, waste_recoded, value, engage, attend))

scale_scores <- cleaned_data %>%
  mutate(opt_eventscore = (worthwhile + waste_recoded + value + engage + attend)/5) %>%
  select(-waste, -sum_eventscore, -avg_eventscore)

ggplot(scale_scores, aes(x = type, y = opt_eventscore, fill = format)) + geom_boxplot()

model_scaled <- lm(opt_eventscore ~ type*format, data = scale_scores)
anova(model_scaled)
leveneTest(opt_eventscore ~ type*format, data = scale_scores)
#Fixes the unequal variances problem, but still nothing significant
```

```{r}
ggplot(scale_scores, aes(x = type, y = worthwhile, fill = format)) + geom_boxplot()
ggplot(scale_scores, aes(x = type, y = waste_recoded, fill = format)) + geom_boxplot()
ggplot(scale_scores, aes(x = type, y = value, fill = format)) + geom_boxplot()
ggplot(scale_scores, aes(x = type, y = engage, fill = format)) + geom_boxplot()
ggplot(scale_scores, aes(x = type, y = attend, fill = format)) + geom_boxplot()


#Looking only at academic and business, with value as a response
no_soc <- scale_scores %>%
  filter(type != "social")
no_soc_value <- lm(value ~ type*format, data = no_soc)
anova(no_soc_value)
leveneTest(value~ type*format, data = no_soc)
plot(no_soc_value, which = 2)
plot(no_soc_value, which = 1)

#Looking at engagement as a response
engagement <- lm(engage ~ type*format, data = scale_scores)
#I think that stands up even after Bonferroni
anova(engagement)
leveneTest(engage ~ type*format, data = scale_scores)
plot(engagement, which = 2)
qplot(engagement$residuals, geom = "histogram", binwidth = 0.5)
TukeyHSD(aov(engage ~ type, data = scale_scores))
TukeyHSD(aov(engage ~ type*format, data = scale_scores))

#Looking at waste - nothing in the normal, barely scraped into significance if you exclude social
#but it's close enough that any multiple comparisons correction will make it insignificant
waste <- lm(waste_recoded ~ type*format, data = scale_scores)
anova(waste)
waste_b <- lm(waste_recoded ~ type*format, data = no_soc)
anova(waste_b)
leveneTest(waste_recoded ~ type*format, data = scale_scores)

#I personally don't see differences in many of the others that would be close enough to significant to try, but who knows
```